# ベースイメージ
FROM python:3.8

# 作業ディレクトリの設定
WORKDIR /app

# 必要なパッケージのインストール
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# ソースコードをコンテナ内にコピー
COPY . .

# サーバーを起動
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
